blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/<slug:slug>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/<slug:slug>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete')
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField(verbose_name='Текст статьи')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    slug = models.CharField(max_length=200, verbose_name='slug', **NULLABLE)
    preview = models.ImageField(upload_to='blog_previews/', verbose_name='Превью', **NULLABLE)
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания', **NULLABLE)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/views.py
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog
from django.urls import reverse_lazy, reverse


# Create your views here.

class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'is_published', 'preview')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.slug = slugify(self.object.title)
        self.object.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'is_published', 'preview')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.slug = slugify(self.object.title)
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', kwargs={'pk': self.object.pk, 'slug': self.object.slug})


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
          <div class ='card'>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить статью "{{ object.title }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить
                    </button>
                    <a href="{% url 'blog:list' %}" class="btn btn-warning">Отменить</a>
                </form>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="card-body">
    <h1>{{ object.title }}</h1>
    {% if object.creation_date %}
    <p><strong>Дата создания:</strong> {{ object.creation_date }}</p>
    {% endif %}
    <p>{{ object.body }}</p>
    {% if object.preview %}
    <img src="{{ object.preview.url }}" alt="Preview Image" style="max-width: 100%;">
    {% endif %}
    <div class="card-footer">
        Просмотры: {{ object.views_count }}
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
          <div class ='card'>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Создать</button>
                </form>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-lg btn-block btn-outline-primary mb-3" href="{% url 'blog:create' %}">Добавить статью</a>
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4 mb-4">
            <div class="card box-shadow">
                {% if object.preview %}
                <img src="{{ object.preview.url }}" class="card-img-top" alt="Preview Image" style="height: 200px; width: auto; display: block; object-fit: cover;">
                {% endif %}
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ object.body}}</p>
                    <a class="btn btn-sm btn-block btn-outline-primary" href="{% url 'blog:view' pk=object.pk slug=object.slug %}">Подробнее</a>
                    <a class="btn btn-sm btn-block btn-outline-primary" href="{% url 'blog:edit' pk=object.pk slug=object.slug %}">изменить</a>
                    <a class="btn btn-sm btn-block btn-outline-primary" href="{% url 'blog:delete' object.pk %}">удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}