blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/<slug:slug>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/<slug:slug>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import CatalogListView, CatalogDetailView, ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, ProductTemplateView
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', CatalogListView.as_view(), name='index'),
    path('category/<int:pk>/', ProductListView.as_view(), name='category_list'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('contacts/', ProductTemplateView.as_view(), name='contacts'),
    path('<int:pk>/', cache_page(60)(CatalogDetailView.as_view()), name='item_detail')
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, RegisterMessageView, CustomLoginView, email_verification, PasswordResetView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='confirm_register'),
    path('register/message/', RegisterMessageView.as_view(), name='SuccessRegister'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/message/', PasswordResetView.as_view(), name='password_reset_message'),
]

catalog/models.py
from django.db import models
from config import settings
from users.models import User
# Create your models here.
NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(upload_to='product_images/', verbose_name="Изображение", **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="Категория")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создано")
    last_updated = models.DateTimeField(auto_now=True, verbose_name="Обновлено")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL, **NULLABLE, verbose_name='Автор')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f"Название: {self.name}"

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-created_at', ]


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return f'Название: {self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    version_number = models.CharField(max_length=100, verbose_name="Версия продукта")
    version_name = models.CharField(max_length=100, verbose_name="Название версии")
    is_active = models.BooleanField(default=False, verbose_name="Актуальная версия")

    def __str__(self):
        return f"Версия {self.version_number} - {self.version_name} для {self.product.name}"

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image', 'category', 'owner')

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')

        if name and description:
            forbidden_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция",
                               "радар"]
            for word in forbidden_words:
                if word.lower() in name.lower() or word.lower() in description.lower():
                    self.add_error(None, forms.ValidationError(
                        f'Слово "{word}" не допускается в названии или описании продукта.'))

        return cleaned_data

    def save(self, commit=True):
        product = super().save(commit=False)
        if commit:
            product.save()


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class ProductModeratorForm(forms.ModelForm):
    is_published = forms.BooleanField(label='Опубликовать', required=False, widget=forms.RadioSelect(choices=(
        (True, 'Да'),
        (False, 'Нет'),
    )))

    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image', 'category', 'is_published',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.forms import inlineformset_factory, RadioSelect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Category, Product, Version
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import VersionForm
from catalog.services import get_product_from_cache


def get_active_version(product):
    active_version = Version.objects.filter(product=product, is_active=True).first()
    return active_version


class ModeratorAccessMixin(AccessMixin):
    """
    Миксин для проверки доступа модератора или выше к неопубликованным материалам.
    """
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_superuser or request.user.is_staff or request.user.groups.filter(name__in=['moderator']).exists():
                return super().dispatch(request, *args, **kwargs)
            else:
                # Пользователь не является модератором, суперпользователем или персоналом
                # поэтому мы фильтруем только опубликованные материалы
                self.queryset = self.get_queryset().filter(is_published=True)
                return super().dispatch(request, *args, **kwargs)
        else:
            return self.handle_no_permission()


# Create your views here.
class CatalogListView(ListView):
    model = Category
    extra_context = {
        'title': 'Тест магазин'
    }

    def get_queryset(self):
        return get_product_from_cache()


class ProductListView(LoginRequiredMixin,ModeratorAccessMixin, ListView):
    model = Product
    context_object_name = 'products'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        # Добавляем логику для получения активной версии для каждого продукта
        products = context_data['products']
        for product in products:
            active_version = get_active_version(product)
            product.active_version = active_version

        # Добавляем логику для получения информации о категории, если требуется
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk

        # Добавляем флаг для модераторов, указывающий, является ли текущий пользователь модератором
        context_data['is_moderator'] = self.request.user.groups.filter(name='moderator').exists()

        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object is not None:
            self.object.owner = self.request.user
            self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('catalog:index')  # Redirect to some other URL


class ProductUpdateView(LoginRequiredMixin, ModeratorAccessMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormSet(self.request.POST, instance=self.object)
        else:
            formset = VersionFormSet(instance=self.object)
        context_data['formset'] = formset
        active_version = get_active_version(self.object)
        context_data['active_version'] = active_version
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            formset.save()
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='moderator').exists():
            return ProductModeratorForm
        else:
            return ProductForm

    def get_success_url(self):
        return reverse_lazy('catalog:index')  # Redirect to some other URL

    def test_func(self):
        product = self.get_object()
        user = self.request.user
        return product.owner == user or user.is_superuser or user.groups.filter(name='moderator').exists()


class ProductDeleteView(DeleteView):
    model = Product

    def get_success_url(self):
        return reverse_lazy('catalog:category_list', kwargs={'pk': self.object.category.pk})


class CatalogDetailView(DetailView):
    model = Product


class ProductTemplateView(TemplateView):
    template_name = 'catalog/contacts.html'


def contacts(request):
    if request.method == 'POST':
        name = request.POST['name']
        phone = request.POST['phone']
        message = request.POST['message']
        print(name, phone, message)
    return render(request, 'catalog/contacts.html')

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
   {% include 'catalog/menu.html' %}
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Тест-Магазинчик</h1>
    <p class="lead">Описание тестового магазина</p>
</div>

<div class="container">
    <div class="row text-center">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Тест-Магазинчик
                <small class="d-block mb-3 text-muted">{% now "Y" %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>

                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class = 'col-12'>
 {% if user.is_authenticated %}
  <a href="{% url 'catalog:product_create' %}" class="btn btn-lg btn-block btn-outline-primary">Добавить товар</a>
{% endif %}

</div>
<div class="container">
  <div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
      <div class="card mb-4 box-shadow h-100">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body d-flex flex-column">
          <img src="{{ object.image | my_media_filter }}" class="card-img-top img-fluid" style="object-fit: cover; height: 200px;">
          <h1 class="card-title pricing-card-title">{{ object.price }}</h1>
          <ul class="list-unstyled mt-3 mb-4 text-start">
            <li>{{ object.description|truncatechars:100 }}</li>
          </ul>
          <a class="btn btn-lg btn-block btn-outline-primary mt-auto" href="{% url 'catalog:category_list' object.pk %}">Подробнее</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}


<h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
<div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>

{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
  <div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
      <div class="card mb-4 box-shadow h-100">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body d-flex flex-column">
          <img src="{{ object.image | my_media_filter }}" class="card-img-top img-fluid" style="object-fit: cover; height: 200px;">
          <h1 class="card-title pricing-card-title">{{ object.price }}</h1>
          <ul class="list-unstyled mt-3 mb-4 text-start">
            <li>{{ object.description|truncatechars:100 }}</li>
          </ul>
          <a class="btn btn-lg btn-block btn-outline-primary mt-auto" href="{% url 'catalog:item_detail' object.pk %}">Подробнее</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

catalog/templates/catalog/menu.html
 <h5 class="my-0 mr-md-auto font-weight-normal">Тест магазинчик</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Новости</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
       {% if user.is_authenticated %}
    <form class="p-2 btn btn-outline-primary" method="post" action="{% url 'users:logout' %}">
    {% csrf_token %}
    <button type="submit">Выход</button>
</form>
{% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
{% endif %}

    </nav>

catalog/templates/catalog/page_item.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div>
    <h1>{{ object.name }}</h1>
    <p>Стоимость: <br>{{ object.price }}руб.</p>
    <img src="{{ object.image | my_media_filter }}">
    <p>{{ object.description }}</p>
    {% if object.active_version %}
              <li>Актуальная версия: {{ object.active_version.version_number }} - {{ object.active_version.version_name }}</li>
            {% else %}
              <li>Неактуальная версия</li>
            {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
          <div class ='card'>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить товар "{{ object.title }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить
                    </button>
                    <a class="btn btn-lg btn-block btn-outline-primary mt-auto" href="{% url 'catalog:category_list' object.category.pk %}">Отменить</a>
                </form>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div>
    <h1>{{ object.name }}</h1>
    <p>Стоимость: <br>{{ object.price }}руб.</p>
    <img src="{{ object.image | my_media_filter }}">
    <p>{{ object.description }}</p>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h5 class="mb-0">
                            {% if object %}
                                Редактировать объект
                            {% else %}
                                Создать новый объект
                            {% endif %}
                        </h5>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block mt-3">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
            {% if object %}
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                        {% endfor %}
                    </div>
                </div>
            </div>
             {% endif %}
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
 {% if user.is_authenticated %}
  <a href="{% url 'catalog:product_create' %}" class="btn btn-lg btn-block btn-outline-primary">Добавить товар</a>
{% endif %}
  <div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
      <div class="card mb-4 box-shadow h-100">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body d-flex flex-column">
          <img src="{{ object.image | my_media_filter }}" class="card-img-top img-fluid" style="object-fit: cover; height: 200px;">
          <h1 class="card-title pricing-card-title">{{ object.price }}</h1>
          <ul class="list-unstyled mt-3 mb-4 text-start">
            <li>{{ object.description|truncatechars:100 }}</li>
            {% if object.active_version %}
              <li>Актуальная версия: {{ object.active_version.version_number }} - {{ object.active_version.version_name }}</li>
            {% else %}
              <li>Неактуальная версия</li>
            {% endif %}
          </ul>
          <a class="btn btn-link" href="{% url 'catalog:item_detail' object.pk %}">Подробнее</a>
         {% if user == object.owner or user.is_superuser or is_moderator %}
          <a class="btn btn-link" href="{% url 'catalog:product_update' pk=object.pk %}">Редактировать</a>
          <a class="btn btn-link" href="{% url 'catalog:product_delete' pk=object.pk %}">Удалить</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}